// Code generated by tdt2go
// DO NOT EDIT! ANY CHANGES MAY BE OVERWRITTEN.

package job

// COMPSsApplication is the generated representation of org.eflows4hpc.pycompss.plugin.types.COMPSsApplication data type
type COMPSsApplication struct {
	Arguments     []string         `mapstructure:"arguments" json:"arguments,omitempty"`
	Command       string           `mapstructure:"command" json:"command,omitempty"`
	ContainerOpts ContainerOptions `mapstructure:"container_opts" json:"container_opts,omitempty"`
}

// ContainerOptions is the generated representation of org.eflows4hpc.pycompss.plugin.types.ContainerOptions data type
type ContainerOptions struct {
	ContainerCompssPath string `mapstructure:"container_compss_path" json:"container_compss_path,omitempty"`
	ContainerImage      string `mapstructure:"container_image" json:"container_image,omitempty"`
	ContainerOpts       string `mapstructure:"container_opts" json:"container_opts,omitempty"`
}

// Environment is the generated representation of org.eflows4hpc.pycompss.plugin.types.Environment data type
type Environment struct {
	// The endpoint of the pycomps server
	Endpoint string `mapstructure:"endpoint" json:"endpoint,omitempty"`
	// user used to connect to the cluster may be overridden by a workflow input
	UserName string `mapstructure:"user_name" json:"user_name,omitempty"`
}

// SubmissionParams is the generated representation of org.eflows4hpc.pycompss.plugin.types.SubmissionParams data type
type SubmissionParams struct {
	CompssModules     []string `mapstructure:"compss_modules" json:"compss_modules,omitempty"`
	ExtraCompssOpts   string   `mapstructure:"extra_compss_opts" json:"extra_compss_opts,omitempty"`
	NumNodes          int      `mapstructure:"num_nodes" json:"num_nodes,omitempty"`
	PythonInterpreter string   `mapstructure:"python_interpreter" json:"python_interpreter,omitempty"`
	Qos               string   `mapstructure:"qos" json:"qos,omitempty"`
}
