

# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run.
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build
        uses: docker://golang:1
        with:
          args: /bin/bash -c "CGO_ENABLED=0 go build ."
        env:
          XDG_CACHE_HOME: /tmp/.cache
          HOME: /tmp/buildhome

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: pycompss-yorc-plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
